"""Auto-generated by glue-airflow-local. Do not edit by hand."""

from datetime import datetime

from airflow import DAG

from glue_airflow_local.operators import MockGlueJobOperator

with DAG(
    dag_id="simple-etl",
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["glue-airflow-local"],
) as dag:
    extract_job = MockGlueJobOperator(
        task_id="extract_job",
        job_name="extract-job",
        default_params={'INPUT_BUCKET': 'local-input', 'INPUT_KEY': 'sample-input.csv', 'STAGING_BUCKET': 'local-staging', 'OUTPUT_BUCKET': 'local-output', 'ENV': 'local'},
    )
    load_job = MockGlueJobOperator(
        task_id="load_job",
        job_name="load-job",
        default_params={'INPUT_BUCKET': 'local-input', 'INPUT_KEY': 'sample-input.csv', 'STAGING_BUCKET': 'local-staging', 'OUTPUT_BUCKET': 'local-output', 'ENV': 'local'},
    )
    transform_job = MockGlueJobOperator(
        task_id="transform_job",
        job_name="transform-job",
        default_params={'INPUT_BUCKET': 'local-input', 'INPUT_KEY': 'sample-input.csv', 'STAGING_BUCKET': 'local-staging', 'OUTPUT_BUCKET': 'local-output', 'ENV': 'local'},
    )
    transform_job >> load_job
    extract_job >> transform_job
