"""Translate a Workflow IR into an Airflow DAG Python source file."""

from __future__ import annotations

import keyword
import logging
import re
from collections import defaultdict
from io import StringIO

from glue_airflow_local.exceptions import UnsupportedTriggerError
from glue_airflow_local.model import (
    JobState,
    LogicalOperator,
    TriggerType,
    Workflow,
)
from glue_airflow_local.validator import validate_workflow

_LOG = logging.getLogger(__name__)


def translate_workflow(workflow: Workflow, *, workflow_dir: str) -> str:
    """Return Python source for an Airflow DAG that mirrors `workflow`."""
    validate_workflow(workflow)
    _check_translation_supported(workflow)

    schedule = _pick_schedule(workflow)
    upstreams = _build_upstream_map(workflow)

    out = StringIO()
    out.write(_HEADER)
    out.write("\n")
    out.write("with DAG(\n")
    out.write(f'    dag_id="{workflow.name}",\n')
    if schedule is None:
        out.write("    schedule=None,\n")
    else:
        out.write(f"    schedule={schedule!r},\n")
    out.write("    start_date=datetime(2024, 1, 1),\n")
    out.write("    catchup=False,\n")
    out.write('    tags=["glue-airflow-local"],\n')
    out.write(") as dag:\n")

    var_for: dict[str, str] = {}
    used: dict[str, int] = {}
    for job in sorted(workflow.jobs):
        base = _identifier(job)
        if base in used:
            used[base] += 1
            var = f"{base}_{used[base]}"
        else:
            used[base] = 0
            var = base
        var_for[job] = var
        out.write(f"    {var} = MockGlueJobOperator(\n")
        out.write(f'        task_id="{var}",\n')
        out.write(f'        job_name="{job}",\n')
        out.write(f"        workflow_dir={workflow_dir!r},\n")
        out.write("    )\n")

    for downstream, ups in sorted(upstreams.items()):
        for up in sorted(ups):
            out.write(f"    {var_for[up]} >> {var_for[downstream]}\n")

    return out.getvalue()


_HEADER = '''"""Auto-generated by glue-airflow-local. Do not edit by hand."""

from datetime import datetime

from airflow import DAG

from glue_airflow_local.operators import MockGlueJobOperator
'''


def _pick_schedule(workflow: Workflow) -> str | None:
    scheduled = [t for t in workflow.triggers if t.type is TriggerType.SCHEDULED]
    if not scheduled:
        return None
    if len(scheduled) > 1:
        _LOG.warning(
            "Workflow %r has %d SCHEDULED triggers; using the first (%r) as DAG schedule",
            workflow.name,
            len(scheduled),
            scheduled[0].name,
        )
    return scheduled[0].schedule


def _check_translation_supported(workflow: Workflow) -> None:
    """Reject IR features that the v0.1 translator can't faithfully express."""
    for trig in workflow.triggers:
        if trig.type is TriggerType.CONDITIONAL and trig.predicate is not None:
            if trig.predicate.logical is LogicalOperator.OR:
                raise UnsupportedTriggerError(
                    f"Trigger {trig.name!r}: OR predicates are not supported in v0.1 "
                    f"(would require Airflow TriggerRule or branching). "
                    f"Use multiple separate CONDITIONAL triggers, one per condition."
                )
            for cond in trig.predicate.conditions:
                if cond.state is not JobState.SUCCEEDED:
                    raise UnsupportedTriggerError(
                        f"Trigger {trig.name!r}: condition state {cond.state.value!r} "
                        f"is not supported in v0.1 (only SUCCEEDED). v0.2 will map "
                        f"FAILED/TIMEOUT/STOPPED to Airflow trigger rules."
                    )


def _build_upstream_map(workflow: Workflow) -> dict[str, set[str]]:
    upstreams: dict[str, set[str]] = defaultdict(set)
    for trig in workflow.triggers:
        if trig.type is TriggerType.CONDITIONAL and trig.predicate is not None:
            ups = {c.job_name for c in trig.predicate.conditions}
            for action in trig.actions:
                upstreams[action.job_name].update(ups)
    return upstreams


_NON_IDENT = re.compile(r"[^A-Za-z0-9_]")


def _identifier(job_name: str) -> str:
    """Convert 'extract-job' -> 'extract_job' so it's a valid Python identifier."""
    cleaned = _NON_IDENT.sub("_", job_name)
    if cleaned and cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    if keyword.iskeyword(cleaned) or keyword.issoftkeyword(cleaned):
        cleaned = f"{cleaned}_"
    return cleaned or "task"
